"""complete phase 3 crm core fields

Revision ID: ee53324e3b46
Revises: 044856b5d8f7
Create Date: 2026-08-09 16:09:45.078581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee53324e3b46'
down_revision: Union[str, None] = '044856b5d8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_phone'), 'companies', ['phone'], unique=False)
    op.create_index(op.f('ix_companies_website'), 'companies', ['website'], unique=False)
    op.add_column('contacts', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('description', sa.Text(), nullable=True))
    op.execute(
        """
        UPDATE contacts
        SET
            first_name = COALESCE(NULLIF(split_part(name, ' ', 1), ''), 'Unknown'),
            last_name = NULLIF(trim(substr(name, length(split_part(name, ' ', 1)) + 2)), '')
        WHERE first_name IS NULL
        """
    )
    op.alter_column('contacts', 'first_name', existing_type=sa.String(length=100), nullable=False)
    op.create_index(op.f('ix_contacts_first_name'), 'contacts', ['first_name'], unique=False)
    op.create_index(op.f('ix_contacts_job_title'), 'contacts', ['job_title'], unique=False)
    op.create_index(op.f('ix_contacts_last_name'), 'contacts', ['last_name'], unique=False)
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    op.add_column('leads', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('estimated_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.execute("UPDATE leads SET title = name WHERE title IS NULL")
    op.alter_column('leads', 'title', existing_type=sa.String(length=255), nullable=False)
    op.create_index(op.f('ix_leads_title'), 'leads', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_title'), table_name='leads')
    op.drop_column('leads', 'estimated_value')
    op.drop_column('leads', 'description')
    op.drop_column('leads', 'title')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_last_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_job_title'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_first_name'), table_name='contacts')
    op.drop_column('contacts', 'description')
    op.drop_column('contacts', 'last_name')
    op.drop_column('contacts', 'first_name')
    op.drop_index(op.f('ix_companies_website'), table_name='companies')
    op.drop_index(op.f('ix_companies_phone'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'website')
    # ### end Alembic commands ###
